before_script:
  - cp app/config/parameters_test.yml.ci app/config/parameters_test.yml
  - cp app/config/parameters_test.yml.ci app/config/parameters.yml

init:app:
  script:
  - ant vendors
  - ant prepare-db
  - ant assetic
  - ant clear-cache

test:app:
  script:
  - ant functional