before_script:
  - cp app/config/parameters_test.yml.ci app/config/parameters_test.yml
  - cp app/config/parameters_test.yml.ci app/config/parameters.yml

stages:
  - build
  - test
  - deploy

app-init:
  stage: build
  script:
  - ant vendors
  - ant prepare-db
  - ant assetic
  - ant clear-cache

app-test:unit:
  stage: test
  script:
  - ant vendors
  - ant prepare-db
  - ant assetic
  - ant clear-cache
  - ant phpunit
  cache:
    untracked: true

app-test:functional:
  stage: test
  script:
  - ant vendors
  - ant prepare-db
  - ant assetic
  - ant clear-cache
  - ant functional

app-deploy:
  stage: deploy
  script:
  - echo OK
  when: manual