before_script:
  - cp app/config/parameters_test.yml.ci app/config/parameters_test.yml
  - cp app/config/parameters_test.yml.ci app/config/parameters.yml

stages:
  - test
  - deploy

app-test:
  stage: test
  script:
  - ant vendors
  - ant prepare-db
  - ant assetic
  - ant clear-cache
  - ant phpunit
  - ant functional
  except:
  - master
  
app-test-deploy:
  stage: deploy
  script:
  - sudo /home/www/xcoding/stock-test/update.sh
  - robot --variable user:admin --variable pass:123qwe --variable url:test.stock.t.x-coding.pl -d /home/www/xcoding/stock-test/web /home/www/xcoding/stock-test/selenium.robot
  only:
  - develop

#app-test:
#  stage: test
#  script:
#  - ant vendors
#  - ant prepare-db
#  - ant assetic
#  - ant clear-cache
#  - ant phpunit
#  - ant functional
#  cache:
#    untracked: true

#app-test:functional:
#  stage: test
#  script:
#  - ant vendors
#  - ant prepare-db
#  - ant assetic
#  - ant clear-cache
#  - ant functional

app-prod-deploy:
  stage: deploy
  script:
  - sudo /home/www/xcoding/stock/update.sh
  - robot --variable user:admin --variable pass:123qwe --variable url:stock.t.x-coding.pl -d /home/www/xcoding/stock/web /home/www/xcoding/stock/selenium.robot
  when: manual
  only:
  - master