fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

craue_config_settings:
    resource: "@CraueConfigBundle/Resources/config/routing/settings.xml"
    prefix: /settings