imports:
    - { resource: "@AppBundle/Resources/config/use_case.yml" }

services:   
  app.loader.report_loader:
    class: Report\Loader\ReportLoader
    arguments:
      - '@doctrine.orm.entity_manager'

  app.loader.parser_report_loader:
    class: Report\Loader\ParserReportLoader
    arguments:
      - '@doctrine.orm.entity_manager'

  app.reader.form_report_reader:
    class: Report\Reader\FormReportReader
    
  app.reader.parser_report_reader:
    class: Report\Reader\ParserReportReader  

  app.report.parser:
    class: Report\Parser\Biznesradar\BiznesradarParser
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('ReportContext:Report')"
      - '@app.reader.parser_report_reader'
      - '@logger'

  app.downloader.bossa_downloader:
    class: Price\Downloader\BossaDownloader

  app.translator.bossa_market_id_translator:
    class: Company\Translator\BossaMarketIdTranslator

  app.filter.bossa_filter:
    class: Price\Filter\BossaFilter
    arguments:
      - '@app.translator.bossa_market_id_translator'

  app.parser.bossa_parser:
    class: Price\Parser\BossaParser
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('CompanyContext:Company')"
      - '@app.translator.bossa_market_id_translator'
