imports:
    - { resource: "@AppBundle/Resources/config/use_case.yml" }

services:
  app.loader.report_loader:
    class: AppBundle\Loader\ReportLoader
    arguments:
      - '@doctrine.orm.entity_manager'

  app.reader.form_report_reader:
    class: AppBundle\Reader\FormReportReader
