services:
  app.use_case.list_companies:
    class: AppBundle\UseCase\ListCompanies
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Company')"

  app.use_case.get_company:
    class: AppBundle\UseCase\GetCompany
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Company')"