services:
  app.use_case.list_companies:
    class: Application\UseCase\ListCompanies
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('CompanyContext:Company')"

  app.use_case.get_company:
    class: Application\UseCase\GetCompany
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('CompanyContext:Company')"

  app.use_case.get_price:
    class: Application\UseCase\GetPrice
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('PriceContext:Price')"

  app.use_case.get_report:
    class: Application\UseCase\GetReport
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('ReportContext:Report')"

  app.use_case.add_report_manually:
    class: Application\UseCase\AddReport
    arguments:
      - '@app.reader.form_report_reader'
      - '@app.loader.report_loader'

  app.use_case.pull_price:
    class: Application\UseCase\PullPrice
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@app.downloader.bossa_downloader'
      - '@app.filter.bossa_filter'
      - '@app.parser.bossa_parser'

  app.use_case.pull_all_prices:
    class: Application\UseCase\PullAllPrices
    arguments:
      - '@app.use_case.pull_price'
      - "@=service('doctrine.orm.entity_manager').getRepository('CompanyContext:Company')"
      
  app.use_case.get_company_online_annual_reports:
    class: Application\UseCase\GetCompanyOnlineAnnualReports
    arguments:
      - '@app.report.parser'
      - '@app.loader.parser_report_loader'
      
  app.use_case.get_company_online_quarterly_reports:
    class: Application\UseCase\GetCompanyOnlineQuarterlyReports
    arguments:
      - '@app.report.quarterly_parser'
      - '@app.loader.parser_report_loader'