services:
  app.use_case.list_companies:
    class: AppBundle\UseCase\ListCompanies
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Company')"

  app.use_case.get_company:
    class: AppBundle\UseCase\GetCompany
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Company')"

  app.use_case.list_reports:
    class: AppBundle\UseCase\ListReports
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Report')"

  app.use_case.add_report_manually:
    class: AppBundle\UseCase\AddReport
    arguments:
      - '@app.reader.form_report_reader'
      - '@app.loader.report_loader'