<?php
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Company\Entity\Company;
use Company\Entity\Company\Type;

class LoadCompanyData implements OrderedFixtureInterface, FixtureInterface
{

    private $manager;

    public function getOrder()
    {
        return 1;
    }

    public function load(ObjectManager $manager)
    {
        $this->manager = $manager;
        
        $this->addWig30Companies();
        $this->addWigBudowCompanies();
        
        $this->manager->flush();
    }

    private function addCompany($name, $id, $type = Type::ORDINARY)
    {
        $company = new Company($name, $id, $type);
        
        $this->manager->persist($company);
    }

    private function addWig30Companies()
    {
        $this->addCompany("Alior Bank", "ALR", Type::BANK);
        $this->addCompany("Asseco Poland", "ACP");
        $this->addCompany("Bank Millenium", "MIL", Type::BANK);
        $this->addCompany("Bogdanka", "LWB");
        $this->addCompany("BZ WBK", "BZW", Type::BANK);
        $this->addCompany("CCC", "CCC");
        $this->addCompany("CD Projekt", "CDR");
        $this->addCompany("Cyfrowy Polsat", "CPS");
        $this->addCompany("ENEA", "ENA");
        $this->addCompany("Energa", "ENG");
        $this->addCompany("Eurocash", "EUR");
        $this->addCompany("Grupa Azoty", "ATT");
        $this->addCompany("Grupa Lotos", "LTS");
        $this->addCompany("GTC", "GTC");
        $this->addCompany("ING Bank Slaski", "ING", Type::BANK);
        $this->addCompany("Jastrzebska Spolka Weglowa", "JSW");
        $this->addCompany("Kernel Holding", "KER");
        $this->addCompany("KGHM Polska Miedz", "KGH");
        $this->addCompany("LPP", "LPP");
        $this->addCompany("MBANK", "MBK", Type::BANK);
        $this->addCompany("Orange Polska", "OPL");
        $this->addCompany("PEKAO", "PEO", Type::BANK);
        $this->addCompany("PGE", "PGE");
        $this->addCompany("PGNiG", "PGN");
        $this->addCompany("PKN Orlen", "PKN");
        $this->addCompany("PKO BP", "PKO", Type::BANK);
        $this->addCompany("PKP Cargo", "PKP");
        $this->addCompany("PZU", "PZU");
        $this->addCompany("Synthos", "SNS");
        $this->addCompany("Tauron Polska Energia", "TPE");
    }

    private function addAllCompanies()
    {
        $this->addCompany("01Cyberaton SA", "01C");
        $this->addCompany("11 bit studios SA", "11B");
        $this->addCompany("2C Partners SA", "2CP");
        $this->addCompany("2Intellect.com SA", "2IT");
        $this->addCompany("4Fun Media SA", "4FM");
        $this->addCompany("4Mobility SA", "4MB");
        $this->addCompany("5TH Avenue Holding SA", "5AH");
        $this->addCompany("71Media SA", "71M");
        $this->addCompany("7FIT SA", "7FT");
        $this->addCompany("A.P.N. Promise SA", "PRO");
        $this->addCompany("AAT Holding SA", "AHL");
        $this->addCompany("AB SA", "ABE");
        $this->addCompany("Abadon Real Estate SA", "ABA");
        $this->addCompany("Abak SA", "ABK");
        $this->addCompany("ABC Data SA", "ABC");
        $this->addCompany("ABM Solid SA", "ABM");
        $this->addCompany("ABS Investment SA", "AIN");
        $this->addCompany("AC SA", "ACG");
        $this->addCompany("Acartus SA", "ACA");
        $this->addCompany("Ackerman SA", "ACK");
        $this->addCompany("Acrebit SA", "ACR");
        $this->addCompany("Action SA w restrukturyzacji", "ACT");
        $this->addCompany("Adform Group SA", "ADF");
        $this->addCompany("Adiuvo Investments SA", "ADV");
        $this->addCompany("Admiral Boats SA", "ADM");
        $this->addCompany("Advertigo SA", "AVE");
        $this->addCompany("Aedes SA w restrukturyzacji", "AED");
        $this->addCompany("AerFinance SE", "AER");
        $this->addCompany("Aforti Holding SA", "AFH");
        $this->addCompany("Agencja Rozwoju Innowacji SA", "ARI");
        $this->addCompany("Agora SA", "AGO");
        $this->addCompany("Agroliga Group PLC", "AGL");
        $this->addCompany("Agromep SA", "AGP");
        $this->addCompany("Agroton Public Limited", "AGT");
        $this->addCompany("Ailleron SA", "ALL");
        $this->addCompany("Airway Medix SA", "AWM");
        $this->addCompany("Aiton Caldwell SA", "AIT");
        $this->addCompany("Akcept Finance SA", "AFC");
        $this->addCompany("Alchemia SA", "ALC");
        $this->addCompany("Alda SA", "ALD");
        $this->addCompany("AlejaSamochodowa.pl SA", "ALS");
        $this->addCompany("Alior Bank SA", "ALR", Type::BANK);
        $this->addCompany("Alkal SA", "ALK");
        $this->addCompany("Alma Market SA w restrukturyzacji", "ALM");
        $this->addCompany("Alta SA", "AAT");
        $this->addCompany("Altus Towarzystwo Funduszy Inwestycyjnych SA", "ALI");
        $this->addCompany("Alumast SA", "ALU");
        $this->addCompany("Alumetal SA", "AML");
        $this->addCompany("Ambra SA", "AMB");
        $this->addCompany("AMICA Wronki SA", "AMC");
        $this->addCompany("Ampli SA w upadłości układowej", "APL");
        $this->addCompany("AmRest Holdings SE", "EAT");
        $this->addCompany("Analizy Online SA", "AOL");
        $this->addCompany("Angel Business Capital SA", "MRA");
        $this->addCompany("Apanet SA", "APA");
        $this->addCompany("Apator SA", "APT");
        $this->addCompany("Apis SA", "ASA");
        $this->addCompany("Aplisens SA", "APN");
        $this->addCompany("APS Energia SA", "APE");
        $this->addCompany("Aqua SA", "AQU");
        $this->addCompany("Aqua SA", "AQA");
        $this->addCompany("Aramus SA", "ARA");
        $this->addCompany("Archicom SA", "ARH");
        $this->addCompany("Arctic Paper SA", "ATC");
        $this->addCompany("Arcus SA", "ARC");
        $this->addCompany("Arena.pl SA", "ARE");
        $this->addCompany("Arrinera SA", "ARX");
        $this->addCompany("Art New Media SA", "ANM");
        $this->addCompany("Arteria SA", "ARR");
        $this->addCompany("Artifex Mundi SA", "ART");
        $this->addCompany("ArtP Capital SA", "TYP");
        $this->addCompany("ASBISc Enterprises PLC", "ASB");
        $this->addCompany("ASM Group SA", "ASM");
        $this->addCompany("Asseco Business Solutions SA", "ABS");
        $this->addCompany("Asseco Poland SA", "ACP");
        $this->addCompany("Asseco South Eastern Europe SA", "ASE");
        $this->addCompany("Assetian SA", "PCV");
        $this->addCompany("Assetus SA", "ASS");
        $this->addCompany("Astarta Holding NV", "AST");
        $this->addCompany("Astro SA", "ASR");
        $this->addCompany("Atal SA", "1AT");
        $this->addCompany("ATC-Cargo SA", "ATA");
        $this->addCompany("Atende SA", "ATD");
        $this->addCompany("Athos Venture Capital SA", "AVC");
        $this->addCompany("Atlanta Poland SA", "ATP");
        $this->addCompany("Atlantis SA", "ATS");
        $this->addCompany("Atlas Estates Limited", "ATL");
        $this->addCompany("ATM Grupa SA", "ATG");
        $this->addCompany("ATM SA", "ATM");
        $this->addCompany("Aton-HT SA", "ATO");
        $this->addCompany("Atrem SA", "ATR");
        $this->addCompany("AUGA Group AB", "AWG");
        $this->addCompany("Auto Partner SA", "APR");
        $this->addCompany("Automatyka-Pomiary-Sterowanie SA", "APS");
        $this->addCompany("Auto-Spa SA", "ASP");
        $this->addCompany("Auxilia SA", "AUX");
        $this->addCompany("Avia Solutions Group AB", "ASG");
        $this->addCompany("AviaAM Leasing AB", "AAL");
        $this->addCompany("AWBUD SA", "AWB");
        $this->addCompany("Aztec International SA", "AZC");
        $this->addCompany("B.A.C.D. SA", "BAC");
        $this->addCompany("B2BPartner SA", "B2B");
        $this->addCompany("B3System SA", "B3S");
        $this->addCompany("Baltic Bridge SA", "WIS");
        $this->addCompany("Baltic Ceramics Investments SA", "BCI");
        $this->addCompany("Balticon SA", "BLT");
        $this->addCompany("Banco Santander SA", "SAN", Type::BANK);
        $this->addCompany("Bank BGŻ BNP Paribas SA", "BGZ", Type::BANK);
        $this->addCompany("Bank Handlowy w Warszawie SA", "BHW", Type::BANK);
        $this->addCompany("Bank Millennium SA", "MIL", Type::BANK);
        $this->addCompany("Bank Ochrony Środowiska SA", "BOS", Type::BANK);
        $this->addCompany("Bank Polska Kasa Opieki SA", "PEO", Type::BANK);
        $this->addCompany("Bank Zachodni WBK SA", "BZW", Type::BANK);
        $this->addCompany("BBI Development SA", "BBD");
        $this->addCompany("BDF SA", "BDF");
        $this->addCompany("Benefit Systems SA", "BFT");
        $this->addCompany("Berling SA", "BRG");
        $this->addCompany("Beskidzkie Biuro Consultingowe SA", "BBA");
        $this->addCompany("Best SA", "BST");
        $this->addCompany("Betacom SA", "BCM");
        $this->addCompany("BGE SA", "BGE");
        $this->addCompany("Binary Helix SA", "BHX");
        $this->addCompany("Bio Planet SA", "BIP");
        $this->addCompany("Bioerg SA", "BER");
        $this->addCompany("BioFactory SA", "BFC");
        $this->addCompany("Biogened SA", "BGD");
        $this->addCompany("Biomass Energy Project SA", "BEP");
        $this->addCompany("Biomax SA", "BIM");
        $this->addCompany("BioMaxima SA", "BMX");
        $this->addCompany("Biomed-Lublin Wytwórnia Surowic i Szczepionek SA", "BML");
        $this->addCompany("Bioton SA", "BIO");
        $this->addCompany("Biuro Inwestycji Kapitałowych SA", "BIK");
        $this->addCompany("Black Pearl SA", "BPC");
        $this->addCompany("Black Point SA", "BPN");
        $this->addCompany("Blirt SA", "BLR");
        $this->addCompany("Bloober Team SA", "BLO");
        $this->addCompany("Blue Tax Group SA", "BTG");
        $this->addCompany("Blumerang Investors SA", "BLU");
        $this->addCompany("bmp Holding AG", "BMP");
        $this->addCompany("BOA SA", "BOA");
        $this->addCompany("Boomerang SA", "BMR");
        $this->addCompany("Boruta-Zachem SA", "BRU");
        $this->addCompany("Boryszew SA", "BRS");
        $this->addCompany("Bowim SA", "BOW");
        $this->addCompany("BPX SA", "BPX");
        $this->addCompany("Bras SA", "BSA");
        $this->addCompany("Braster SA", "BRA");
        $this->addCompany("Briju SA", "BRI");
        $this->addCompany("Broad Gate SA", "BDG");
        $this->addCompany("Browar Czarnków SA", "BRO");
        $this->addCompany("BSC Drukarnia Opakowań SA", "BSC");
        $this->addCompany("Budimex SA", "BDX");
        $this->addCompany("Budopol-Wrocław SA", "BDL");
        $this->addCompany("Bumech SA", "BMC");
        $this->addCompany("Buwog AG", "BWO");
        $this->addCompany("BVT SA", "BVT");
        $this->addCompany("Bytom SA", "BTM");
        $this->addCompany("Calatrava Capital SA", "CTC");
        $this->addCompany("Calesco SA", "CLS");
        $this->addCompany("Call Center Tools SA", "CCT");
        $this->addCompany("Capital Park SA", "CPG");
        $this->addCompany("Capital Partners SA", "CPA");
        $this->addCompany("Carlson Gaudi Investments SA", "MOB");
        $this->addCompany("Cash Flow SA", "CFL");
        $this->addCompany("Caspar Asset Management SA", "CSR");
        $this->addCompany("CCC SA", "CCC");
        $this->addCompany("CD Projekt SA", "CDR");
        $this->addCompany("CDRL SA", "CDL");
        $this->addCompany("Celon Pharma SA", "CLN");
        $this->addCompany("Cenospheres Trade &amp; Engineering SA", "CTE");
        $this->addCompany("Centrum Finansowe Banku BPS SA", "CFB");
        $this->addCompany("Centrum Medyczne Enel-Med SA", "ENE");
        $this->addCompany("Centrum Nowoczesnych Technologii SA", "CNT");
        $this->addCompany("Centrum Wspierania Projektów Europejskich SA", "CWP");
        $this->addCompany("Centuria Group SA", "VEL");
        $this->addCompany("Centurion Finance SA", "CTF");
        $this->addCompany("Ceramika Nowa Gala SA", "CNG");
        $this->addCompany("Cereal Planet Plc", "CRP");
        $this->addCompany("CEZ a.s.", "CEZ");
        $this->addCompany("CFI Holding SA", "CFI");
        $this->addCompany("Chemoservis-Dwory SA", "CHS");
        $this->addCompany("CI Games SA", "CIG");
        $this->addCompany("Ciasteczka z Krakowa SA", "CZK");
        $this->addCompany("Ciech SA", "CIE");
        $this->addCompany("City Service SE", "CTS");
        $this->addCompany("Clean&amp;Carbon Energy SA", "CCE");
        $this->addCompany("Cloud Technologies SA", "CLD");
        $this->addCompany("Coal Energy SA", "CLE");
        $this->addCompany("Cognor Holding SA", "COG");
        $this->addCompany("Colian Holding SA", "COL");
        $this->addCompany("Columbus Energy SA", "CLC");
        $this->addCompany("Comarch SA", "CMR");
        $this->addCompany("Comeco SA", "CMC");
        $this->addCompany("Comp SA", "CMP");
        $this->addCompany("Comperia.pl SA", "CPL");
        $this->addCompany("ComPress SA", "COM");
        $this->addCompany("Concept Liberty Group SA", "LTG");
        $this->addCompany("Copernicus Securities SA", "CRS");
        $this->addCompany("Corelens SA", "COR");
        $this->addCompany("CPD SA", "CPD");
        $this->addCompany("CSY SA", "CSY");
        $this->addCompany("CUBE.ITG SA", "CTG");
        $this->addCompany("Cyfrowe Centrum Serwisowe SA", "CCS");
        $this->addCompany("Cyfrowy Polsat SA", "CPS");
        $this->addCompany("Czerwona Torebka SA", "CZT");
        $this->addCompany("Damf Inwestycje SA", "DIN");
        $this->addCompany("Danks Europejskie Centrum Doradztwa Podatkowego SA", "DNS");
        $this->addCompany("Dase SA", "DFG");
        $this->addCompany("Decora SA", "DCR");
        $this->addCompany("Dekpol SA", "DEK");
        $this->addCompany("Dektra SA", "DKR");
        $this->addCompany("Delko SA", "DEL");
        $this->addCompany("Dent-a-Medical SA", "DAM");
        $this->addCompany("Devoran SA", "DEV");
        $this->addCompany("DGA SA", "DGA");
        $this->addCompany("Digital Avenue SA", "DGL");
        $this->addCompany("Dino Polska SA", "DNP");
        $this->addCompany("Dolnośląskie Centrum Deweloperskie SA", "DCD");
        $this->addCompany("Dom Development SA", "DOM");
        $this->addCompany("Dom Lekarski SA", "DLK");
        $this->addCompany("Dom Maklerski IDM SA w upadłości układowej", "IDM");
        $this->addCompany("Domenomania.pl SA", "DOA");
        $this->addCompany("Doradcy24 SA", "D24");
        $this->addCompany("Drewex SA", "DRE");
        $this->addCompany("Drop SA", "DRP");
        $this->addCompany("Drozapol-Profil SA", "DPL");
        $this->addCompany("Dywilan SA", "DYW");
        $this->addCompany("EastSideCapital SA", "ESC");
        $this->addCompany("easyCALL.pl SA", "ECL");
        $this->addCompany("EBC Solicitors SA", "EBC");
        $this->addCompany("EC2 SA", "EC2");
        $this->addCompany("Echo Investment SA", "ECH");
        $this->addCompany("Ecotech Polska SA", "ECO");
        $this->addCompany("ED Invest SA", "EDI");
        $this->addCompany("Edison SA", "EDN");
        $this->addCompany("Efix Dom Maklerski SA", "EFX");
        $this->addCompany("EGB Investments SA", "EGB");
        $this->addCompany("e-Kiosk SA", "EKS");
        $this->addCompany("Eko Export SA", "EEX");
        $this->addCompany("Ekobox SA", "EBX");
        $this->addCompany("Ekokogeneracja SA", "EKG");
        $this->addCompany("Ekopol Górnośląski Holding SA", "EGH");
        $this->addCompany("Electroceramics SA", "ECR");
        $this->addCompany("Elektrobudowa SA", "ELB");
        $this->addCompany("Elektrociepłownia Będzin SA", "BDZ");
        $this->addCompany("Elektromont SA", "ELM");
        $this->addCompany("Elektrotim SA", "ELT");
        $this->addCompany("Elemental Holding SA", "EMT");
        $this->addCompany("ELKOP SA", "EKP");
        $this->addCompany("ELQ SA", "ELQ");
        $this->addCompany("EMC Instytut Medyczny SA", "EMC");
        $this->addCompany("Emmerson Realty SA", "EMM");
        $this->addCompany("Emperia Holding SA", "EMP");
        $this->addCompany("e-Muzyka SA", "EMU");
        $this->addCompany("Enea SA", "ENA");
        $this->addCompany("ENEFI Energiahatekonysagi Nyrt.", "EST");
        $this->addCompany("Energa SA", "ENG");
        $this->addCompany("ENERGOAPARATURA SA", "ENP");
        $this->addCompany("Energoinstal SA", "ENI");
        $this->addCompany("Energy Environment Solutions SA", "WRE");
        $this->addCompany("Enter Air SA", "ENT");
        $this->addCompany("EO Networks SA", "EON");
        $this->addCompany("Equitier SA", "ETR");
        $this->addCompany("Erbud SA", "ERB");
        $this->addCompany("ERG SA", "ERG");
        $this->addCompany("Ergis SA", "EGS");
        $this->addCompany("Erne Ventures SA", "ERN");
        $this->addCompany("Eskimos SA", "ESK");
        $this->addCompany("Esotiq &amp; Henderson SA", "EAH");
        $this->addCompany("ES-System SA", "ESS");
        $this->addCompany("Eurocash SA", "EUR");
        $this->addCompany("Eurocent SA", "ERC");
        $this->addCompany("Eurohold Bulgaria AD", "EHG");
        $this->addCompany("Euroinvestment SA", "VIV");
        $this->addCompany("Europejski Fundusz Energii SA", "EFE");
        $this->addCompany("Europejskie Centrum Odszkodowań SA", "EUC");
        $this->addCompany("Eurosnack SA", "ECK");
        $this->addCompany("Eurosystem SA", "ERS");
        $this->addCompany("Euro-Tax.pl SA", "ETX");
        $this->addCompany("Eurotel SA", "ETL");
        $this->addCompany("Everest Investments SA", "EVE");
        $this->addCompany("Examobile SA", "EXA");
        $this->addCompany("Excellence SA", "EXC");
        $this->addCompany("Exillon Energy Plc", "EXL");
        $this->addCompany("EZO SA", "EZO");
        $this->addCompany("Fabryka Farb i Lakierów Śnieżka SA", "SKA");
        $this->addCompany("Fabryka Konstrukcji Drewnianych SA", "FKD");
        $this->addCompany("Fabryka Obrabiarek RAFAMET SA", "RAF");
        $this->addCompany("Fabryka Sprzętu i Narzędzi Górniczych Fasing SA", "FSG");
        $this->addCompany("Fabryki Mebli FORTE SA", "FTE");
        $this->addCompany("Fachowcy.pl Ventures SA", "FAV");
        $this->addCompany("FAM SA", "FAM");
        $this->addCompany("Famur SA", "FMF");
        $this->addCompany("Fast Finance SA", "FFI");
        $this->addCompany("Feerum SA", "FEE");
        $this->addCompany("Fenghua SoleTech AG", "FGT");
        $this->addCompany("Ferro SA", "FRO");
        $this->addCompany("Ferrum SA", "FER");
        $this->addCompany("Financial Assets Management Group SA", "FMG");
        $this->addCompany("Finhouse SA", "FIN");
        $this->addCompany("Firma Oponiarska Dębica SA", "DBC");
        $this->addCompany("Fiten SA w restrukturyzacji", "FTN");
        $this->addCompany("Fluid SA", "FLD");
        $this->addCompany("Fon SA", "FON");
        $this->addCompany("Forbuild SA", "BTX");
        $this->addCompany("Forever Entertainment SA", "FOR");
        $this->addCompany("Forposta SA", "FPO");
        $this->addCompany("Fortuna Entertainment Group NV", "FEG");
        $this->addCompany("Fota SA w upadłości układowej", "FOT");
        $this->addCompany("Fundusz Hipoteczny Dom SA", "FHD");
        $this->addCompany("Futuris SA", "FUT");
        $this->addCompany("Galvo SA", "GAL");
        $this->addCompany("GC Investment SA w upadłości układowej", "GCI");
        $this->addCompany("Gekoplast SA", "GKP");
        $this->addCompany("G-Energy SA", "GNG");
        $this->addCompany("Genomed SA", "GEN");
        $this->addCompany("Geo-Term Polska SA", "GTP");
        $this->addCompany("Geotrans SA", "GTS");
        $this->addCompany("Geotrekk SA", "GTK");
        $this->addCompany("Getin Holding SA", "GTN", Type::BANK);
        $this->addCompany("Getin Noble Bank SA", "GNB", Type::BANK);
        $this->addCompany("Giełda Papierów Wartościowych w Warszawie SA", "GPW");
        $this->addCompany("Giełda Praw Majątkowych Vindexus SA", "VIN");
        $this->addCompany("Gino Rossi SA", "GRI");
        $this->addCompany("GKS GieKSa Katowice SA", "GKS");
        $this->addCompany("GLG Pharma SA", "GLG");
        $this->addCompany("Global Cosmed SA", "GLC");
        $this->addCompany("Global Trade SA", "GTR");
        $this->addCompany("Globe Trade Centre SA", "GTC");
        $this->addCompany("GO Towarzystwo Funduszy Inwestycyjnych SA", "GTF");
        $this->addCompany("Gobarto SA", "GOB");
        $this->addCompany("Golab SA", "GOL");
        $this->addCompany("Gorenje gospodinjski aparati d.d.", "GRV");
        $this->addCompany("GPPI SA", "GPP");
        $this->addCompany("Graphic SA", "GRP");
        $this->addCompany("Graviton Capital SA", "GRT");
        $this->addCompany("Grempco SA", "GRM");
        $this->addCompany("Griffin Premium RE", "GPR");
        $this->addCompany("Groclin SA", "GCN");
        $this->addCompany("Grodno SA", "GRN");
        $this->addCompany("Grupa Azoty SA", "ATT");
        $this->addCompany("Grupa Azoty Zakłady Azotowe Puławy SA", "ZAP");
        $this->addCompany("Grupa Azoty Zakłady Chemiczne Police SA", "PCE");
        $this->addCompany("Grupa Emmerson SA", "GEM");
        $this->addCompany("Grupa Exorigo-Upos SA", "GEU");
        $this->addCompany("Grupa HRC SA", "HRC");
        $this->addCompany("Grupa Jaguar SA", "GJA");
        $this->addCompany("Grupa Kapitałowa Immobile SA", "GKI");
        $this->addCompany("Grupa Kęty SA", "KTY");
        $this->addCompany("Grupa Lotos SA", "LTS");
        $this->addCompany("Grupa Recykl SA", "GRC");
        $this->addCompany("Grupa Trinity SA", "GTY");
        $this->addCompany("Grupa Żywiec SA", "ZWC");
        $this->addCompany("Gwarant Agencja Ochrony SA", "GWR");
        $this->addCompany("Harper Hygienics SA", "HRP");
        $this->addCompany("Hawe SA w restrukturyzacji", "HWE");
        $this->addCompany("Hefal Serwis SA w restrukturyzacji", "HEF");
        $this->addCompany("Helio SA", "HEL");
        $this->addCompany("Herkules SA", "HRS");
        $this->addCompany("Hetan Technologies SA", "HTN");
        $this->addCompany("HFT Group SA", "HFT");
        $this->addCompany("HM Inwest SA", "HMI");
        $this->addCompany("Hollywood SA", "HLD");
        $this->addCompany("Hortico SA", "HOR");
        $this->addCompany("Hotblok SA", "HOT");
        $this->addCompany("HubStyle SA", "HUB");
        $this->addCompany("Hurtimex SA", "HRT");
        $this->addCompany("Hydrapres SA", "HPS");
        $this->addCompany("Hyperion SA", "HYP");
        $this->addCompany("i2 Development SA", "I2D");
        $this->addCompany("i3D SA", "I3D");
        $this->addCompany("IAI SA", "IAI");
        $this->addCompany("iAlbatros Group SA", "IAG");
        $this->addCompany("IBC Polska F&amp;P SA", "IBC");
        $this->addCompany("IBSM SA", "IBS");
        $this->addCompany("ICP Group SA", "ICP");
        $this->addCompany("Idea Bank SA", "IDA", Type::BANK);
        $this->addCompany("Ideon SA", "IDE");
        $this->addCompany("IDH SA", "IDH");
        $this->addCompany("IFIRMA SA", "IFI");
        $this->addCompany("IFM Global Funds SA", "IFM");
        $this->addCompany("iFun4all SA", "IF4");
        $this->addCompany("Igoria Trade SA", "IGT");
        $this->addCompany("Imagis SA w restrukturyzacji", "IMG");
        $this->addCompany("IMC SA", "IMC");
        $this->addCompany("Immofinanz AG", "IIA");
        $this->addCompany("Impel SA", "IPL");
        $this->addCompany("Impera Capital SA", "IMP");
        $this->addCompany("Impexmetal SA", "IPX");
        $this->addCompany("IMS SA", "IMS");
        $this->addCompany("Inbook SA", "INB");
        $this->addCompany("INC SA", "INC");
        $this->addCompany("Incana SA", "ICA");
        $this->addCompany("Indata SA", "IDT");
        $this->addCompany("Indos SA", "INS");
        $this->addCompany("IndygoTech Minerals SA", "IDG");
        $this->addCompany("Indykpol SA", "IND");
        $this->addCompany("InfoScan SA", "IST");
        $this->addCompany("Infosystems SA", "IFS");
        $this->addCompany("Infra SA", "IFA");
        $this->addCompany("ING Bank Śląski SA", "ING", Type::BANK);
        $this->addCompany("Inno-Gene SA", "IGN");
        $this->addCompany("Innovative Commerce a.s.", "ICM");
        $this->addCompany("InPost SA", "IPT");
        $this->addCompany("Inpro SA", "INP");
        $this->addCompany("Instal Kraków SA", "INK");
        $this->addCompany("Instytut Szkoleń i Analiz Gospodarczych SA", "ISG");
        $this->addCompany("Integer.pl SA", "ITG");
        $this->addCompany("InteliWise SA", "ITL");
        $this->addCompany("Inter Cars SA", "CAR");
        $this->addCompany("Inter Rao Lietuva AB", "IRL");
        $this->addCompany("Interbud-Lublin SA", "ITB");
        $this->addCompany("Intercapital Property Development ADSIC", "ICD");
        $this->addCompany("Interferie SA", "INF");
        $this->addCompany("International Personal Finance PLC", "IPF");
        $this->addCompany("Internet Union SA", "IUS");
        $this->addCompany("Internity SA", "INT");
        $this->addCompany("Intersport  Polska SA", "IPO");
        $this->addCompany("Introl SA", "INL");
        $this->addCompany("Investeko SA", "IVE");
        $this->addCompany("Investment Friends Capital SA", "IFC");
        $this->addCompany("Investment Friends SA", "IFR");
        $this->addCompany("Invico SA w restrukturyzacji", "IVC");
        $this->addCompany("Invista SA", "INV");
        $this->addCompany("Inwestycje Alternatywne Profit SA", "IAP");
        $this->addCompany("Inwestycje.pl SA", "INW");
        $this->addCompany("IPO Doradztwo Kapitałowe SA", "IOD");
        $this->addCompany("Ipopema Securities SA", "IPE");
        $this->addCompany("IQ Partners SA", "IQP");
        $this->addCompany("Izo-Blok SA", "IZB");
        $this->addCompany("Izolacja Jarocin SA", "IZO");
        $this->addCompany("Izostal SA", "IZS");
        $this->addCompany("J.W. Construction Holding SA", "JWC");
        $this->addCompany("Jantar Development SA", "JAN");
        $this->addCompany("Jastrzębska Spółka Węglowa SA", "JSW");
        $this->addCompany("JHM Development SA", "JHM");
        $this->addCompany("JJ Auto AG", "JJO");
        $this->addCompany("JR Holding SA", "JRH");
        $this->addCompany("Jujubee SA", "JJB");
        $this->addCompany("JWA SA", "JWA");
        $this->addCompany("JWW Invest SA", "JWW");
        $this->addCompany("K&amp;K Herbal Poland SA", "KKH");
        $this->addCompany("K2 Internet SA", "K2I");
        $this->addCompany("Kancelaria Medius SA", "KME");
        $this->addCompany("Kancelaria Prawna-Inkaso WEC SA", "KPI");
        $this->addCompany("KBJ SA", "KBJ");
        $this->addCompany("KCI SA", "KCI");
        $this->addCompany("KDM Shipping Public Limited", "KDM");
        $this->addCompany("Kerdos Group SA w restrukturyzacji", "KRS");
        $this->addCompany("Kernel Holding SA", "KER");
        $this->addCompany("KGHM Polska Miedź SA", "KGH");
        $this->addCompany("Kino Polska TV SA", "KPL");
        $this->addCompany("Kleba Invest SA", "KIN");
        $this->addCompany("Klon SA", "KLN");
        $this->addCompany("Kofama Koźle SA", "KFM");
        $this->addCompany("Komputronik SA", "KOM");
        $this->addCompany("Konsorcjum Stali SA", "KST");
        $this->addCompany("KOPEX SA", "KPX");
        $this->addCompany("Korbank SA", "KOR");
        $this->addCompany("Korporacja Budowlana Dom SA", "KBD");
        $this->addCompany("Korporacja Gospodarcza Efekt SA", "EFK");
        $this->addCompany("Korporacja KGL SA", "KGL");
        $this->addCompany("Koszalińskie Przedsiębiorstwo Przemysłu Drzewnego SA", "KPD");
        $this->addCompany("Krakchemia SA", "KCH");
        $this->addCompany("Kredyt Inkaso SA", "KRI");
        $this->addCompany("Krezus SA", "KZS");
        $this->addCompany("Krka d.d.", "KRK");
        $this->addCompany("Kruk SA", "KRU");
        $this->addCompany("Krynica Vitamin SA", "KVT");
        $this->addCompany("Krynicki Recykling SA", "KRC");
        $this->addCompany("KSG Agro SA", "KSG");
        $this->addCompany("Kupiec SA", "KPC");
        $this->addCompany("Labo Print SA", "LAB");
        $this->addCompany("Langloo.com SA", "LAN");
        $this->addCompany("Lark.pl SA", "LRK");
        $this->addCompany("Larq SA", "LRQ");
        $this->addCompany("Laser-Med SA", "LSR");
        $this->addCompany("Lauren Peso Polska SA", "LPS");
        $this->addCompany("LC Corp SA", "LCC");
        $this->addCompany("Lena Lighting SA", "LEN");
        $this->addCompany("Lentex SA", "LTX");
        $this->addCompany("Letus Capital SA", "LET");
        $this->addCompany("Libet SA", "LBT");
        $this->addCompany("LiveChat Software SA", "LVC");
        $this->addCompany("LK Designer Shops SA", "LKS");
        $this->addCompany("Logintrade SA", "LGT");
        $this->addCompany("Logzact SA", "LGZ");
        $this->addCompany("Lokaty Budowlane SA", "LBD");
        $this->addCompany("Lokum Deweloper SA", "LKD");
        $this->addCompany("Loyd SA", "LYD");
        $this->addCompany("LPP SA", "LPP");
        $this->addCompany("LS Tech-Homes SA", "LSH");
        $this->addCompany("LSI Software SA", "LSI");
        $this->addCompany("LUBAWA SA", "LBW");
        $this->addCompany("Lubelski Węgiel Bogdanka SA", "LWB");
        $this->addCompany("LUG SA", "LUG");
        $this->addCompany("Lukardi SA", "LUK");
        $this->addCompany("Luxima SA", "LUX");
        $this->addCompany("LZMO SA w restrukturyzacji", "LZM");
        $this->addCompany("M Food SA", "MFD");
        $this->addCompany("M.W. Trade SA", "MWT");
        $this->addCompany("M4B SA", "M4B");
        $this->addCompany("Mabion SA", "MAB");
        $this->addCompany("Macro Games SA", "MGS");
        $this->addCompany("Macrologic SA", "MCL");
        $this->addCompany("Madkom SA", "MAD");
        $this->addCompany("Magna Polonia SA", "06N");
        $this->addCompany("Makarony Polskie SA", "MAK");
        $this->addCompany("MakoLab SA", "MLB");
        $this->addCompany("Małkowski-Martech SA", "MMA");
        $this->addCompany("Mangata Holding SA", "MGT");
        $this->addCompany("Marie Brizards Wine &amp; Spirits", "MBW");
        $this->addCompany("Marka SA w restrukturyzacji", "MRK");
        $this->addCompany("MarSoft SA", "MAR");
        $this->addCompany("Marvipol SA", "MVP");
        $this->addCompany("Master Pharm SA", "MPH");
        $this->addCompany("Matrx Pharmaceuticals SA", "SP1");
        $this->addCompany("Maximus SA", "MAX");
        $this->addCompany("Maxipizza SA", "MXP");
        $this->addCompany("mBank SA", "MBK", Type::BANK);
        $this->addCompany("MBF Group SA", "MBF");
        $this->addCompany("MCI Capital SA", "MCI");
        $this->addCompany("MDI Energia SA", "MDI");
        $this->addCompany("MedApp SA", "MDA");
        $this->addCompany("Medcamp SA", "MDP");
        $this->addCompany("Med-Galicja SA", "MGC");
        $this->addCompany("MEDIACAP SA", "MCP");
        $this->addCompany("Median Polska SA", "MDN");
        $this->addCompany("Mediatel SA", "MTL");
        $this->addCompany("Medical Cannabis SA", "GNR");
        $this->addCompany("Medicalgorithmics SA", "MDG");
        $this->addCompany("Mega Sonic SA", "MGA");
        $this->addCompany("Megaron SA", "MEG");
        $this->addCompany("Mennica Polska SA", "MNC");
        $this->addCompany("Mennica Skarbowa SA", "MNS");
        $this->addCompany("Mera SA", "MER");
        $this->addCompany("Mercator Medical SA", "MRC");
        $this->addCompany("Mercor SA", "MCR");
        $this->addCompany("Merit Invest SA", "MEI");
        $this->addCompany("Merlin Group SA", "MRG");
        $this->addCompany("Metropolis SA", "MRS");
        $this->addCompany("Mex Polska SA", "MEX");
        $this->addCompany("MFO SA", "MFO");
        $this->addCompany("MGM Systems SA", "MGM");
        $this->addCompany("Midven SA", "MID");
        $this->addCompany("Milestone Medical Inc.", "MMD");
        $this->addCompany("Milkiland NV", "MLK");
        $this->addCompany("Milkpol SA", "MLP");
        $this->addCompany("Mineral Midrange SA", "MND");
        $this->addCompany("Minox SA", "MNX");
        $this->addCompany("Miraculum SA", "MIR");
        $this->addCompany("Mirbud SA", "MRB");
        $this->addCompany("MLP Group SA", "MLG");
        $this->addCompany("MM Conferences SA", "MMC");
        $this->addCompany("MNI SA", "MNI");
        $this->addCompany("Mobile Partner SA", "MBP");
        $this->addCompany("MobiMedia Solution SA", "MMS");
        $this->addCompany("Mo-Bruk SA", "MBR");
        $this->addCompany("Mode SA", "MOE");
        $this->addCompany("Modecom SA", "MOD");
        $this->addCompany("Modern Commerce SA", "MCE");
        $this->addCompany("MOJ SA", "MOJ");
        $this->addCompany("MOL Magyar Olaj - és Gázipari Részvénytársaság", "MOL");
        $this->addCompany("Momo SA", "MOM");
        $this->addCompany("Monday Development SA", "MDV");
        $this->addCompany("Money Makers TFI SA", "MMF");
        $this->addCompany("Monnari Trade SA", "MON");
        $this->addCompany("Morizon SA", "MZN");
        $this->addCompany("MOSTOSTAL Płock SA", "MSP");
        $this->addCompany("Mostostal Warszawa SA", "MSW");
        $this->addCompany("Mostostal Zabrze SA", "MSZ");
        $this->addCompany("Motoricus SA", "MTR");
        $this->addCompany("mPay SA", "MPY");
        $this->addCompany("MPL Verbum SA", "VER");
        $this->addCompany("Mr Hamburger SA", "MRH");
        $this->addCompany("M-TRANS SA", "MTS");
        $this->addCompany("MUZA SA", "MZA");
        $this->addCompany("MVA Green Energy SA", "GRE");
        $this->addCompany("Nanotel SA w restrukturyzacji", "NAN");
        $this->addCompany("NAVIMOR-INVEST SA", "NIN");
        $this->addCompany("Neptis SA", "YAN");
        $this->addCompany("Nestmedic SA", "NST");
        $this->addCompany("Netia SA", "NET");
        $this->addCompany("Netmedia SA", "NEM");
        $this->addCompany("Netwise SA", "NTW");
        $this->addCompany("Neuca SA", "NEU");
        $this->addCompany("New World Resources Plc", "NWR");
        $this->addCompany("Newag SA", "NWG");
        $this->addCompany("North Coast SA", "NCT");
        $this->addCompany("Notoria Serwis SA", "NTS");
        $this->addCompany("Novavis SA", "NVV");
        $this->addCompany("Novina SA", "NOV");
        $this->addCompany("NOVITA SA", "NVT");
        $this->addCompany("Nowoczesna Firma SA", "NFP");
        $this->addCompany("NTT System SA", "NTT");
        $this->addCompany("NWAI Dom Maklerski SA", "NWA");
        $this->addCompany("Octava SA", "08N");
        $this->addCompany("Odlewnie Polskie SA", "ODL");
        $this->addCompany("OEX SA", "OEX");
        $this->addCompany("Olympic Entertainment Group AS", "OEG");
        $this->addCompany("Onico SA", "ONC");
        $this->addCompany("Open Finance SA", "OPF");
        $this->addCompany("Open-Net SA", "OPE");
        $this->addCompany("Oponeo.pl SA", "OPN");
        $this->addCompany("OPTeam SA", "OPM");
        $this->addCompany("Optizen Labs SA", "OPT");
        $this->addCompany("Orange Polska SA", "OPL");
        $this->addCompany("Orbis SA", "ORB");
        $this->addCompany("Orco Property Group SA", "OPG");
        $this->addCompany("Organic Farma Zdrowia SA", "ORG");
        $this->addCompany("Orion Investment SA", "ORN");
        $this->addCompany("Orphée SA", "ORP");
        $this->addCompany("Orzeł Biały SA", "OBL");
        $this->addCompany("Orzeł SA", "ORL");
        $this->addCompany("OT Logistics SA", "OTS");
        $this->addCompany("Outdoorzy SA", "OUT");
        $this->addCompany("Ovostar Union N.V.", "OVO");
        $this->addCompany("P.A. Nova SA", "NVA");
        $this->addCompany("Paged SA", "PGD");
        $this->addCompany("Pamapol SA", "PMP");
        $this->addCompany("Parcel Technik SA", "PTE");
        $this->addCompany("Partner-Nieruchomości SA", "PRN");
        $this->addCompany("Patent Fund SA", "PFD");
        $this->addCompany("Patentus SA", "PAT");
        $this->addCompany("PBG SA", "PBG");
        $this->addCompany("PBS Finanse SA", "PBF");
        $this->addCompany("PC Guard SA", "PCG");
        $this->addCompany("PCC Exol SA", "PCX");
        $this->addCompany("PCC Intermodal SA", "PCI");
        $this->addCompany("PCC Rokita SA", "PCR");
        $this->addCompany("Pegas Nonwovens SA", "PGS");
        $this->addCompany("Peixin International Group NV", "PEX");
        $this->addCompany("Pelion SA", "PEL");
        $this->addCompany("Pemug SA", "PMG");
        $this->addCompany("Perma-Fix Medical SA", "PFM");
        $this->addCompany("Petrolinvest SA", "OIL");
        $this->addCompany("Pfleiderer Group SA", "PFL");
        $this->addCompany("PGE Polska Grupa Energetyczna SA", "PGE");
        $this->addCompany("PGS Software SA", "PSW");
        $this->addCompany("Pharmena SA", "PHR");
        $this->addCompany("Photon Energy N.V.", "PEN");
        $this->addCompany("PIK SA", "PIK");
        $this->addCompany("Pilab SA", "PIL");
        $this->addCompany("Pixel Venture Capital SA", "PXC");
        $this->addCompany("PKP Cargo SA", "PKP");
        $this->addCompany("Planet Innovation Group SA", "PIG");
        $this->addCompany("Plasma System SA", "PSM");
        $this->addCompany("Platige Image SA", "PLI");
        $this->addCompany("Platynowe Inwestycje SA", "PIW");
        $this->addCompany("PlayWay SA", "PLW");
        $this->addCompany("Plaza Centers NV", "PLZ");
        $this->addCompany("PMPG Polskie Media SA", "PGM");
        $this->addCompany("Polcolorit SA", "PLT");
        $this->addCompany("Polenergia SA", "PEP");
        $this->addCompany("Polimex-Mostostal SA", "PXM");
        $this->addCompany("Polman SA", "PLM");
        $this->addCompany("Polmed SA", "POM");
        $this->addCompany("Polnord SA", "PND");
        $this->addCompany("Polscy Inwestorzy SA", "PIS");
        $this->addCompany("Polska Grupa Odlewnicza SA", "PGO");
        $this->addCompany("Polska Grupa Przemysłowa Polonit SA", "PGP");
        $this->addCompany("Polska Meat SA", "PME");
        $this->addCompany("Polski Bank Komórek Macierzystych SA", "BKM");
        $this->addCompany("Polski Holding Nieruchomości SA", "PHN");
        $this->addCompany("Polski Koncern Naftowy Orlen SA", "PKN");
        $this->addCompany("Polskie Górnictwo Naftowe i Gazownictwo SA", "PGN");
        $this->addCompany("Polskie Towarzystwo Wspierania Przedsiębiorczości SA", "PTW");
        $this->addCompany("Poltronic SA", "PTN");
        $this->addCompany("Polwax SA", "PWX");
        $this->addCompany("Powszechna Kasa Oszczędności Bank Polski SA", "PKO", Type::BANK);
        $this->addCompany("Powszechny Zakład Ubezpieczeń SA", "PZU");
        $this->addCompany("Pozbud T&amp;R SA", "POZ");
        $this->addCompany("Poznańska Korporacja Budowlana Pekabex SA", "PBX");
        $this->addCompany("Pragma Faktoring SA", "PRF");
        $this->addCompany("Pragma Inkaso SA", "PRI");
        $this->addCompany("Prairie Mining Ltd.", "PDZ");
        $this->addCompany("Premium Food Restaurants SA", "PFR");
        $this->addCompany("Premium Fund SA", "PMF");
        $this->addCompany("Present24 SA", "P24");
        $this->addCompany("Presto SA", "PST");
        $this->addCompany("Prima Moda SA", "PMA");
        $this->addCompany("Prime Car Management SA", "PCM");
        $this->addCompany("Prime Minerals SA", "PMT");
        $this->addCompany("Private Equity Managers SA", "PEM");
        $this->addCompany("Procad SA", "PRD");
        $this->addCompany("Prochem SA", "PRM");
        $this->addCompany("PROJPRZEM SA", "PJP");
        $this->addCompany("Pro-Log SA", "PRL");
        $this->addCompany("Property Lease Fund SA w restrukturyzacji", "PLE");
        $this->addCompany("Protektor SA", "PRT");
        $this->addCompany("Provecta IT SA", "PRV");
        $this->addCompany("Próchnik SA", "PRC");
        $this->addCompany("Prymus SA", "PRS");
        $this->addCompany("Przedsiębiorstwo Handlu Zagranicznego Baltona SA", "BAL");
        $this->addCompany("Przedsiębiorstwo Hydrauliki Siłowej Hydrotor SA", "HDR");
        $this->addCompany("Przedsiębiorstwo Modernizacji Urządzeń Energetycznych REMAK SA", "RMK");
        $this->addCompany("Przedsiębiorstwo Produkcyjno Handlowe Wadex SA", "WAX");
        $this->addCompany("Przedsiębiorstwo Produkcyjno-Handlowe Kompap SA", "KMP");
        $this->addCompany("Przedsiębiorstwo Przemysłu Betonów PREFABET - Białe Błota SA", "PBB");
        $this->addCompany("Przedsiębiorstwo Przemysłu Spożywczego PEPEES SA", "PPS");
        $this->addCompany("Przedsiębiorstwo Telekomunikacyjne Telgam SA", "TLG");
        $this->addCompany("Przetwórstwo Tworzyw Sztucznych Plast-Box SA", "PLX");
        $this->addCompany("Pylon SA", "PYL");
        $this->addCompany("PZ Cormay SA", "CRM");
        $this->addCompany("Quantum Software SA", "QNT");
        $this->addCompany("Quark Ventures SA", "QRK");
        $this->addCompany("Quart Development SA", "QRT");
        $this->addCompany("QubicGames SA", "QUB");
        $this->addCompany("Quercus Towarzystwo Funduszy Inwestycyjnych SA", "QRS");
        $this->addCompany("Qumak SA", "QMK");
        $this->addCompany("Radpol SA", "RDL");
        $this->addCompany("RAFAKO SA", "RFK");
        $this->addCompany("Rainbow Tours SA", "RBW");
        $this->addCompany("RAJDY 4x4 SA", "4X4");
        $this->addCompany("Rank Progress SA", "RNK");
        $this->addCompany("Rawlplug SA", "RWL");
        $this->addCompany("Read-Gene SA", "RDG");
        $this->addCompany("Redan SA", "RDN");
        $this->addCompany("Redwood Holding SA", "RWD");
        $this->addCompany("Regnon SA", "REG");
        $this->addCompany("Reinhold Europe AB", "RHD");
        $this->addCompany("Relpol SA", "RLP");
        $this->addCompany("Remedis SA", "REM");
        $this->addCompany("Remor Solar Polska SA", "AGR");
        $this->addCompany("Resbud SA", "RES");
        $this->addCompany("Revitum SA", "REV");
        $this->addCompany("Robinson Europe SA", "RBS");
        $this->addCompany("Robyg SA", "ROB");
        $this->addCompany("Rocca SA", "RCA");
        $this->addCompany("Ronson Europe N.V.", "RON");
        $this->addCompany("Rotopino.pl SA", "ROT");
        $this->addCompany("Rovita SA", "ROV");
        $this->addCompany("RSY SA", "RSY");
        $this->addCompany("Rubicon Partners SA", "RBC");
        $this->addCompany("Ruch Chorzów SA", "RCW");
        $this->addCompany("Runicom SA", "RUN");
        $this->addCompany("S4E SA", "S4E");
        $this->addCompany("Sadovaya Group SA", "SGR");
        $this->addCompany("Sakana SA", "SKN");
        $this->addCompany("Sanok Rubber Company SA", "SNK");
        $this->addCompany("Sanwil Holding SA", "SNW");
        $this->addCompany("Sapling SA", "SAP");
        $this->addCompany("Sare SA", "SAR");
        $this->addCompany("SCO-PAK SA w restrukturyzacji", "SCO");
        $this->addCompany("Seco/Warwick SA", "SWG");
        $this->addCompany("Seka SA", "SEA");
        $this->addCompany("Seko SA", "SEK");
        $this->addCompany("Selena FM SA", "SEL");
        $this->addCompany("Selvita SA", "SLV");
        $this->addCompany("Serinus Energy Inc.", "SEN");
        $this->addCompany("Sescom SA", "SES");
        $this->addCompany("Setanta SA", "SET");
        $this->addCompany("Sevenet SA", "SEV");
        $this->addCompany("SFD SA", "SFD");
        $this->addCompany("SferaNET SA", "SFN");
        $this->addCompany("Sfinks Polska SA", "SFS");
        $this->addCompany("Silesia One SA", "SSO");
        $this->addCompany("Silva Capital Group SA", "SCG");
        $this->addCompany("Silvano Fashion Group AS", "SFG");
        $this->addCompany("SIMPLE SA", "SME");
        $this->addCompany("Site SA", "STE");
        $this->addCompany("Skarbiec Holding SA", "SKH");
        $this->addCompany("Skoczowska Fabryka Kapeluszy Polkap SA", "SFK");
        $this->addCompany("SKOTAN SA", "SKT");
        $this->addCompany("Skyline Investment SA", "SKL");
        $this->addCompany("SMS Kredyt Holding SA", "SMS");
        $this->addCompany("Softblue SA", "SBE");
        $this->addCompany("Soho Development SA", "SHD");
        $this->addCompany("SOLAR Company SA", "SOL");
        $this->addCompany("Sonel SA", "SON");
        $this->addCompany("Sopharma AD", "SPH");
        $this->addCompany("Spark VC SA", "SPK");
        $this->addCompany("Stalexport Autostrady SA", "STX");
        $this->addCompany("Stalprodukt SA", "STP");
        $this->addCompany("STALPROFIL SA", "STF");
        $this->addCompany("Standrew SA", "STD");
        $this->addCompany("Stanusch Technologies SA", "STT");
        $this->addCompany("Star Fitness SA", "SFI");
        $this->addCompany("Starhedge SA", "SHG");
        $this->addCompany("Stelmet SA", "STL");
        $this->addCompany("Stem Cells Spin SA", "SCS");
        $this->addCompany("Stopklatka SA", "STK");
        $this->addCompany("Stoppoint SA", "PRK");
        $this->addCompany("Summa Linguae SA", "SUL");
        $this->addCompany("Sunex SA", "SNX");
        $this->addCompany("Suntech SA", "SUN");
        $this->addCompany("Surfland Systemy Komputerowe SA", "SSK");
        $this->addCompany("Suwary SA", "SUW");
        $this->addCompany("Swissmed Centrum Zdrowia SA", "SWD");
        $this->addCompany("Swissmed Prywatny Serwis Medyczny SA", "SWP");
        $this->addCompany("Sygnity SA", "SGN");
        $this->addCompany("Symbio Polska SA", "SYM");
        $this->addCompany("Synektik SA", "SNT");
        $this->addCompany("Synthos SA", "SNS");
        $this->addCompany("Szar SA", "SZR");
        $this->addCompany("Talanx AG", "TNX");
        $this->addCompany("Talex SA", "TLX");
        $this->addCompany("Tamex Obiekty Sportowe SA", "TOS");
        $this->addCompany("Tarczyński SA", "TAR");
        $this->addCompany("Tatry Mountain Resorts AS", "TMR");
        $this->addCompany("Tauron Polska Energia SA", "TPE");
        $this->addCompany("TAX-NET SA", "TXN");
        $this->addCompany("Taxus Fund SA", "TXF");
        $this->addCompany("T-Bull SA", "TBL");
        $this->addCompany("Tech Invest Group SA", "TIG");
        $this->addCompany("Techmadex SA", "TDX");
        $this->addCompany("Telemedycyna Polska SA", "TMP");
        $this->addCompany("Telesto SA", "TLO");
        $this->addCompany("Telestrada SA", "TLS");
        $this->addCompany("Teliani Valley Polska SA", "TLV");
        $this->addCompany("Termo2Power SA", "T2P");
        $this->addCompany("Termoexpert SA", "TME");
        $this->addCompany("Termo-Rex SA", "TRR");
        $this->addCompany("Tesgas SA", "TSG");
        $this->addCompany("The Farm 51 Group SA", "F51");
        $this->addCompany("TIM SA", "TIM");
        $this->addCompany("Torpol SA", "TOR");
        $this->addCompany("Tower Investments SA", "TOW");
        $this->addCompany("Toya SA", "TOA");
        $this->addCompany("Trakcja PRKiI SA", "TRK");
        $this->addCompany("Trans Polonia SA", "TRN");
        $this->addCompany("Triton Development SA", "TRI");
        $this->addCompany("TrophyResort Nyrt.", "TPR");
        $this->addCompany("TXM SA", "TXM");
        $this->addCompany("UHY ECA SA", "ECA");
        $this->addCompany("ULMA Construccion Polska SA", "ULM");
        $this->addCompany("Unibep SA", "UNI");
        $this->addCompany("UniCredit S.p.A.", "UCG", Type::BANK);
        $this->addCompany("Unified Factory SA", "UFC");
        $this->addCompany("Unima 2000 Systemy Teleinformatyczne SA", "U2K");
        $this->addCompany("Unimot SA", "UNT");
        $this->addCompany("United SA", "UTD");
        $this->addCompany("Uniwheels AG", "UNW");
        $this->addCompany("Ursus SA", "URS");
        $this->addCompany("Vakomtek SA", "VKT");
        $this->addCompany("Vantage Development SA", "VTG");
        $this->addCompany("Varsav VR SA", "VVR");
        $this->addCompany("Vedia SA", "VED");
        $this->addCompany("Venture Capital Poland SA", "VCP");
        $this->addCompany("Venture Inc SA", "VTI");
        $this->addCompany("Verbicom SA", "VRB");
        $this->addCompany("Verte SA", "VTE");
        $this->addCompany("Viatron SA", "VIA");
        $this->addCompany("Vidis SA", "VDS");
        $this->addCompany("Vigo System SA", "VGO");
        $this->addCompany("Vistal Gdynia SA", "VTL");
        $this->addCompany("Vistula Group SA", "VST");
        $this->addCompany("Vivid Games SA", "VVD");
        $this->addCompany("Voicetel Communications SA", "VOI");
        $this->addCompany("Votum SA", "VOT");
        $this->addCompany("Voxel SA", "VOX");
        $this->addCompany("Warimpex Finanz &amp; und Beteiligungs AG", "WXF");
        $this->addCompany("Wasko SA", "WAS");
        $this->addCompany("WAWEL SA", "WWL");
        $this->addCompany("WDB Brokerzy Ubezpieczeniowi SA", "WDB");
        $this->addCompany("WDX SA", "WDX");
        $this->addCompany("Wealth Bay SA", "WBY");
        $this->addCompany("Werth-Holz SA", "WHH");
        $this->addCompany("Wielton SA", "WLT");
        $this->addCompany("Wierzyciel SA", "WRL");
        $this->addCompany("Wikana SA", "WIK");
        $this->addCompany("Wilbo SA", "WLB");
        $this->addCompany("Wirtualna Polska Holding SA", "WPL");
        $this->addCompany("Wistil SA", "WST");
        $this->addCompany("Wittchen SA", "WTN");
        $this->addCompany("WODKAN Przedsiębiorstwo Wodociągów i Kanalizacji SA", "WOD");
        $this->addCompany("Wojas SA", "WOJ");
        $this->addCompany("Work Service SA", "WSE");
        $this->addCompany("XPlus SA", "XPL");
        $this->addCompany("XSystem SA", "XSM");
        $this->addCompany("X-Trade Brokers Dom Maklerski SA", "XTB");
        $this->addCompany("Yolo SA", "YOL");
        $this->addCompany("Zakład Budowy Maszyn Zremb-Chojnice SA", "ZRE");
        $this->addCompany("Zakłady Automatyki POLNA SA", "PLA");
        $this->addCompany("Zakłady Magnezytowe Ropczyce SA", "RPC");
        $this->addCompany("Zakłady Mięsne Henryk Kania SA", "KAN");
        $this->addCompany("Zakłady Przemysłu Cukierniczego Otmuchów SA", "OTM");
        $this->addCompany("Zakłady Tłuszczowe Kruszwica SA", "KSW");
        $this->addCompany("Zakłady Urządzeń Komputerowych Elzab SA", "ELZ");
        $this->addCompany("Zakłady Urządzeń Kotłowych Stąporków SA", "ZUK");
        $this->addCompany("Zamet Industry SA", "ZMT");
        $this->addCompany("ZASTAL SA", "ZST");
        $this->addCompany("Zespół Elektrociepłowni Wrocławskich Kogeneracja SA", "KGN");
        $this->addCompany("Zespół Elektrowni Pątnów-Adamów-Konin SA", "ZEP");
        $this->addCompany("ZPUE SA", "PUE");
        $this->addCompany("ZUE SA", "ZUE");
    }

    private function addWigBudowCompanies()
    {
        $this->addCompany("Elektrobudowa", "ELB");
    }
}